<div class="container">
    <?php if ($this->error): ?>
        <p class="error"><?php echo $this->error; ?></p>
        <?php
    endif;

    $form = $this->form;
    $form->prepare();
    $form->setAttributes(array(
        'action' => $this->url(NULL, array('controller' => 'Signup', 'action' => 'signup')),
        'enctype' => 'multipart/form-data',
        'class' => 'form-signin',
        'role' => 'form'
    ));
    //$form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>
    <h2>Signup form</h2>
    <?php
    echo $this->formElement($form->get('firstName'));
    echo $this->formElementErrors($form->get('firstName'));
    echo $this->formElement($form->get('secondName'));
    echo $this->formElementErrors($form->get('secondName'));
    echo $this->formElement($form->get('patrName'));
    echo $this->formElementErrors($form->get('patrName'));
    echo $this->formElement($form->get('email'));
    echo $this->formElementErrors($form->get('email'));
    echo $this->formElement($form->get('password'));
    echo $this->formElementErrors($form->get('password'));
    echo $this->formElement($form->get('password-repeat'));
    echo $this->formElementErrors($form->get('password-repeat'));
    ?>
    <p id="pass-match-error" class="error"></p>
    <?php
    echo $this->formElement($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
</div>

<script src="/js/register.js" type="text/javascript"></script>