<div class="container">
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttributes(array(
        'action' => $this->url(NULL, array('controller' => 'login', 'action' => 'login')),
        'enctype' => 'multipart/form-data',
        'class' => 'form-signin',
        'role' => 'form'
    ));
    $formLabel = $this->plugin('formLabel');
    //$form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>
    <h2>Login form</h2>
    <?php
    echo $this->formElement($form->get('email'));
    echo $this->formElementErrors($form->get('email'));
    echo $this->formElement($form->get('password'));
    echo $this->formElementErrors($form->get('password'));
    ?>
    <label class="checkbox" for="<?php echo $form->get('remember-me')->getAttribute('id'); ?>">
        <?php
        echo $this->formElement($form->get('remember-me'));
        echo $form->get('remember-me')->getLabel();
        ?>
    </label>
    <?php
    echo $this->formElement($form->get('submit'));
    echo $this->formElementErrors($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
</div>