<div class="container">
    <?php if ($this->error): ?>
        <p class="error">There were one or more issues with your submission. Please correct them as indicated below.</p>
        <?php
    endif;

    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array('controller' => 'Register', 'action' => 'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>
        
    <h2>Register</h2>
    
    <?php
    echo $this->formElement($form->get('name'));
    echo $this->formElementErrors($form->get('name'));

    echo $this->formElement($form->get('email'));
    echo $this->formElementErrors($form->get('email'));

    echo $this->formElement($form->get('password'));
    echo $this->formElementErrors($form->get('password'));

    echo $this->formElement($form->get('confirm_password'));
    echo $this->formElementErrors($form->get('confirm_password'));

    echo $this->formElement($form->get('submit'));
    echo $this->formElementErrors($form->get('submit'));

    echo $this->form()->closeTag();
    ?>
    <a href="/users"><< Back to Home</a>
</div>